<?php

// ==========================================
// CONFIGURATION
// ==========================================
$botToken = "8966086403:AAFIYinO8Yz_DNLf0TzZq-odFeN223GxnRo"; // আপনার বটের টোকেন এখানে দিন
$website = "https://api.telegram.org/bot" . $botToken;

// ==========================================
// RECEIVE WEBHOOK DATA
// ==========================================
$content = file_get_contents("php://input");
$update = json_decode($content, TRUE);

if (!$update) {
    exit; // No data received
}

$chatId = $update["message"]["chat"]["id"];
$message = $update["message"]["text"];
$messageId = $update["message"]["message_id"];

// ==========================================
// COMMAND HANDLER: /gen
// ==========================================
if (strpos($message, "/gen") === 0) {
    
    // BIN বের করা (e.g., /gen 4532 -> 4532)
    $binInput = trim(substr($message, 5));
    
    // যদি BIN না দেয়, ডিফল্ট বা এরর মেসেজ
    if (empty($binInput) || !is_numeric(str_replace('x', '', strtolower($binInput)))) {
        sendMessage($chatId, "⚠️ **Please provide a valid BIN.**\nExample: `/gen 453210`", $messageId);
        exit;
    }

    // কার্ড জেনারেট লজিক শুরু
    $quantity = 10; // ডিফল্ট ১০টি কার্ড জেনারেট করবে
    $cards = [];

    for ($i = 0; $i < $quantity; $i++) {
        $cc = generateCreditCard($binInput);
        $month = str_pad(rand(1, 12), 2, '0', STR_PAD_LEFT);
        $currentYear = date('y');
        $year = $currentYear + rand(1, 5); // বর্তমান বছর থেকে ৫ বছর পর্যন্ত
        
        // Amex হলে CVV ৪ সংখ্যার, অন্যথায় ৩ সংখ্যার
        $isAmex = (substr($cc, 0, 2) == '34' || substr($cc, 0, 2) == '37');
        $cvv = $isAmex ? rand(1000, 9999) : rand(100, 999);

        // Pipe Format: cc|mm|yy|cvv
        $cards[] = "<code>$cc|$month|$year|$cvv</code>";
    }

    // রেসপন্স সাজানো
    $response = "<b>QRY:</b> $binInput\n";
    $response .= "<b>Amount:</b> $quantity\n\n";
    $response .= implode("\n", $cards);
    $response .= "\n\n<b>Generated by CC Generator</b>";

    sendMessage($chatId, $response, $messageId);
}

// ==========================================
// FUNCTIONS (CORE LOGIC)
// ==========================================

function sendMessage($chatId, $text, $replyTo = null) {
    global $website;
    $url = $website . "/sendMessage?chat_id=" . $chatId . "&text=" . urlencode($text) . "&parse_mode=HTML&reply_to_message_id=" . $replyTo;
    file_get_contents($url);
}

// Luhn Algorithm ব্যবহার করে কার্ড জেনারেট ফাংশন
function generateCreditCard($bin) {
    // 'x' থাকলে সেগুলোকে রেন্ডম সংখ্যা দিয়ে রিপ্লেস করা
    $bin = strtolower($bin);
    $result = "";
    for ($i = 0; $i < strlen($bin); $i++) {
        if ($bin[$i] == 'x') {
            $result .= rand(0, 9);
        } else {
            $result .= $bin[$i];
        }
    }
    $bin = $result;

    // কার্ডের লেংথ নির্ধারণ (Amex হলে ১৫, বাকি সব ১৬)
    $length = 16;
    if (substr($bin, 0, 2) == '34' || substr($bin, 0, 2) == '37') {
        $length = 15;
    }

    // BIN এর পরের বাকি সংখ্যাগুলো রেন্ডম জেনারেট করা (চেক ডিজিট ছাড়া)
    $generateLength = $length - strlen($bin) - 1;
    while ($generateLength > 0) {
        $bin .= rand(0, 9);
        $generateLength--;
    }

    // Luhn Check Digit ক্যালকুলেট করা
    $checkDigit = calculateLuhnCheckDigit($bin);
    
    return $bin . $checkDigit;
}

// Luhn Check Digit ক্যালকুলেশন
function calculateLuhnCheckDigit($number) {
    $sum = 0;
    $alt = true;
    // ডান দিক থেকে বামে লুপ
    for ($i = strlen($number) - 1; $i >= 0; $i--) {
        $n = intval($number[$i]);
        if ($alt) {
            $n *= 2;
            if ($n > 9) {
                $n -= 9;
            }
        }
        $sum += $n;
        $alt = !$alt;
    }
    
    $remainder = $sum % 10;
    if ($remainder == 0) {
        return 0;
    } else {
        return 10 - $remainder;
    }
}

?>
